import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Image src="/logo.svg" alt="Vercel Logo" width={122} height={50} />
        <h1 className={styles.title}>Dove</h1>

        <p className={styles.description}>Talk, share, connect.</p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Already on Dove? &rarr;</h2>
            <p>Login</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>New on Dove? &rarr;</h2>
            <p>Register</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          <span className={styles.logo}>Dove ©2021</span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
